### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION'

### ISSUE THREAD

**Issue by AntonSax** [jiupinjia/stylized-neural-painting#19]
Trying to run the following line 

`python demo_prog.py --img_path [MY_PICTURE] --canvas_color 'white' --max_m_strokes 500 --max_divide 5 --renderer oilpaintbrush --renderer_checkpoint_dir checkpoints_G_oilpaintbrush --net_G zou-fusion-net`

Receiving this error:

```
Traceback (most recent call last):
  File "demo_prog.py", line 5, in <module>
    from painter import *
  File "C:\Users\Tony\Documents\Projects\Personal Projects\stylized-neural-painting\painter.py", line 5, in <module>
    import utils
  File "C:\Users\Tony\Documents\Projects\Personal Projects\stylized-neural-painting\utils.py", line 12, in <module>
    import torchvision.transforms.functional as TF
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\__init__.py", line 2, in <module>
    from torchvision import datasets
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\datasets\__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\datasets\fakedata.py", line 3, in <module>
    from .. import transforms
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\transforms\__init__.py", line 1, in <module>
    from .transforms import *
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\transforms\transforms.py", line 17, in <module>
    from . import functional as F
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'
```

**Comment by AntonSax** [comment]
Found this github page:
[New Pillow version (7.0.0) breaks torchvision (ImportError: cannot import name 'PILLOW_VERSION' from 'PIL')](https://github.com/pytorch/vision/issues/1712)

And a workaround is just to downgrade pillow:
`pip install "pillow<7"`
